export * from './configuracion.interface';
export * from './dia-config.interface';
export * from './espacio-para-config.interface';
export * from './espacio.interface';
export * from './form-espacio.interface';
export * from './franja-horaria.interface';
export * from './imagen.interface';
export * from './novedad.interface';
export * from './tipo-usuario-config.interface';
